//! Pure `CREATE TABLE` generation from catalog-read table definitions. No
//! database access — [`catalog`](super::catalog) reads the structs, this
//! turns them into DSQL-ingestable DDL. Indexes are emitted verbatim from
//! `pg_get_indexdef` elsewhere (dsql-lint normalizes them), so this module
//! only owns the table body.

/// Whether an identity column is `GENERATED ALWAYS` or `GENERATED BY DEFAULT`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IdentityKind {
    Always,
    ByDefault,
}

/// One column of a table, as read from the catalog.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ColumnDef {
    /// Column name (already identifier-validated).
    pub name: String,
    /// `format_type` output, emitted verbatim (e.g. `character varying(50)`).
    pub type_name: String,
    /// `pg_attribute.attnotnull`.
    pub not_null: bool,
    /// `Some` for an identity column; `None` otherwise.
    pub identity: Option<IdentityKind>,
    /// Sequence cache for the identity column. DSQL requires an explicit
    /// `CACHE` (1 or ≥ 65536); ignored when `identity` is `None`.
    pub identity_cache: i64,
    /// `pg_get_expr` of the column default; `None` for identity columns.
    pub default_expr: Option<String>,
}

/// A table to recreate: columns in catalog (attnum) order plus its primary
/// key columns (empty when the table has no PK).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TableDef {
    pub schema: String,
    pub name: String,
    pub columns: Vec<ColumnDef>,
    pub pk_columns: Vec<String>,
}

/// Quote a SQL identifier. Embedded `"` is doubled as defense in depth;
/// callers validate identifiers up front (see `validate_pgdump_identifier`).
fn quote_ident(name: &str) -> String {
    format!("\"{}\"", name.replace('"', "\"\""))
}

/// Render one column's definition (without leading indent or trailing comma).
fn column_line(col: &ColumnDef) -> String {
    let mut s = format!("{} {}", quote_ident(&col.name), col.type_name);
    if let Some(kind) = col.identity {
        // Identity implies NOT NULL, and DSQL requires an explicit CACHE.
        let word = match kind {
            IdentityKind::Always => "ALWAYS",
            IdentityKind::ByDefault => "BY DEFAULT",
        };
        s.push_str(&format!(
            " GENERATED {word} AS IDENTITY (CACHE {})",
            col.identity_cache
        ));
        return s;
    }
    if let Some(default) = &col.default_expr {
        s.push_str(&format!(" DEFAULT {default}"));
    }
    if col.not_null {
        s.push_str(" NOT NULL");
    }
    s
}

/// Generate the `CREATE TABLE` statement for `table`.
pub fn table_ddl(table: &TableDef) -> String {
    let qualified = format!("{}.{}", quote_ident(&table.schema), quote_ident(&table.name));

    let mut lines: Vec<String> = table.columns.iter().map(column_line).collect();
    if !table.pk_columns.is_empty() {
        let cols = table
            .pk_columns
            .iter()
            .map(|c| quote_ident(c))
            .collect::<Vec<_>>()
            .join(", ");
        lines.push(format!("PRIMARY KEY ({cols})"));
    }

    let body = lines
        .iter()
        .map(|l| format!("    {l}"))
        .collect::<Vec<_>>()
        .join(",\n");
    format!("CREATE TABLE {qualified} (\n{body}\n);")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn col(name: &str, type_name: &str) -> ColumnDef {
        ColumnDef {
            name: name.into(),
            type_name: type_name.into(),
            not_null: false,
            identity: None,
            identity_cache: 1,
            default_expr: None,
        }
    }

    #[test]
    fn single_column_table() {
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![col("id", "bigint")],
            pk_columns: vec![],
        };
        assert_eq!(
            table_ddl(&table),
            "CREATE TABLE \"public\".\"t\" (\n    \"id\" bigint\n);"
        );
    }

    #[test]
    fn not_null_and_primary_key() {
        let mut id = col("id", "bigint");
        id.not_null = true;
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![id, col("name", "text")],
            pk_columns: vec!["id".into()],
        };
        assert_eq!(
            table_ddl(&table),
            "CREATE TABLE \"public\".\"t\" (\n    \
             \"id\" bigint NOT NULL,\n    \
             \"name\" text,\n    \
             PRIMARY KEY (\"id\")\n\
             );"
        );
    }

    #[test]
    fn composite_primary_key() {
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![col("a", "integer"), col("b", "integer")],
            pk_columns: vec!["a".into(), "b".into()],
        };
        assert!(table_ddl(&table).contains("PRIMARY KEY (\"a\", \"b\")"));
    }

    #[test]
    fn identity_column_emits_explicit_cache() {
        // DSQL rejects identity columns without an explicit CACHE, so the
        // generator must always emit one. NOT NULL is implied by identity
        // and therefore omitted.
        let id = ColumnDef {
            name: "id".into(),
            type_name: "bigint".into(),
            not_null: true,
            identity: Some(IdentityKind::ByDefault),
            identity_cache: 1,
            default_expr: None,
        };
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![id],
            pk_columns: vec!["id".into()],
        };
        let ddl = table_ddl(&table);
        assert!(
            ddl.contains("\"id\" bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1)"),
            "got: {ddl}"
        );
        // Identity already implies NOT NULL — don't double it up.
        assert!(!ddl.contains("IDENTITY (CACHE 1) NOT NULL"), "got: {ddl}");
    }

    #[test]
    fn identity_always_uses_always_keyword() {
        let id = ColumnDef {
            name: "id".into(),
            type_name: "integer".into(),
            not_null: true,
            identity: Some(IdentityKind::Always),
            identity_cache: 128,
            default_expr: None,
        };
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![id],
            pk_columns: vec![],
        };
        assert!(
            table_ddl(&table).contains("GENERATED ALWAYS AS IDENTITY (CACHE 128)"),
            "got: {}",
            table_ddl(&table)
        );
    }

    #[test]
    fn column_default_is_emitted() {
        let mut status = col("status", "text");
        status.default_expr = Some("'active'::text".into());
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![status],
            pk_columns: vec![],
        };
        assert!(
            table_ddl(&table).contains("\"status\" text DEFAULT 'active'::text"),
            "got: {}",
            table_ddl(&table)
        );
    }
}
