//! Pure `CREATE TABLE` generation from catalog-read table definitions. No
//! database access — [`catalog`](super::catalog) reads the structs, this
//! turns them into DSQL-ingestable DDL. Indexes are emitted verbatim from
//! `pg_get_indexdef` elsewhere (dsql-lint normalizes them), so this module
//! only owns the table body.

/// One column of a table, as read from the catalog.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ColumnDef {
    /// Column name (already identifier-validated).
    pub name: String,
    /// `format_type` output, emitted verbatim (e.g. `character varying(50)`).
    pub type_name: String,
    /// `pg_attribute.attnotnull`.
    pub not_null: bool,
    /// `Some(cache)` for an identity column, carrying its sequence `CACHE`
    /// (DSQL requires an explicit one). Always emitted as `GENERATED BY
    /// DEFAULT` regardless of the source's ALWAYS/BY-DEFAULT kind, because
    /// the loader's reload supplies explicit values.
    pub identity_cache: Option<i64>,
    /// `pg_get_expr` of the column default; `None` for identity columns.
    pub default_expr: Option<String>,
}

/// A table to recreate: columns in catalog (attnum) order plus its primary
/// key columns (empty when the table has no PK).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TableDef {
    pub schema: String,
    pub name: String,
    pub columns: Vec<ColumnDef>,
    pub pk_columns: Vec<String>,
}

use super::quote_ident;

/// Render one column's definition (without leading indent or trailing comma).
fn column_line(col: &ColumnDef) -> String {
    let mut s = format!("{} {}", quote_ident(&col.name), col.type_name);
    if let Some(cache) = col.identity_cache {
        // BY DEFAULT (not ALWAYS) and an explicit CACHE are both load-bearing
        // for DSQL — see `ColumnDef::identity_cache`. Identity implies NOT NULL.
        s.push_str(&format!(
            " GENERATED BY DEFAULT AS IDENTITY (CACHE {cache})"
        ));
        return s;
    }
    if let Some(default) = &col.default_expr {
        s.push_str(&format!(" DEFAULT {default}"));
    }
    if col.not_null {
        s.push_str(" NOT NULL");
    }
    s
}

/// Generate the `CREATE TABLE` statement for `table`.
pub fn table_ddl(table: &TableDef) -> String {
    let qualified = format!(
        "{}.{}",
        quote_ident(&table.schema),
        quote_ident(&table.name)
    );

    let mut lines: Vec<String> = table.columns.iter().map(column_line).collect();
    if !table.pk_columns.is_empty() {
        let cols = table
            .pk_columns
            .iter()
            .map(|c| quote_ident(c))
            .collect::<Vec<_>>()
            .join(", ");
        lines.push(format!("PRIMARY KEY ({cols})"));
    }

    let body = lines
        .iter()
        .map(|l| format!("    {l}"))
        .collect::<Vec<_>>()
        .join(",\n");
    format!("CREATE TABLE {qualified} (\n{body}\n);")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn col(name: &str, type_name: &str) -> ColumnDef {
        ColumnDef {
            name: name.into(),
            type_name: type_name.into(),
            not_null: false,
            identity_cache: None,
            default_expr: None,
        }
    }

    #[test]
    fn single_column_table() {
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![col("id", "bigint")],
            pk_columns: vec![],
        };
        assert_eq!(
            table_ddl(&table),
            "CREATE TABLE \"public\".\"t\" (\n    \"id\" bigint\n);"
        );
    }

    #[test]
    fn not_null_and_primary_key() {
        let mut id = col("id", "bigint");
        id.not_null = true;
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![id, col("name", "text")],
            pk_columns: vec!["id".into()],
        };
        assert_eq!(
            table_ddl(&table),
            "CREATE TABLE \"public\".\"t\" (\n    \
             \"id\" bigint NOT NULL,\n    \
             \"name\" text,\n    \
             PRIMARY KEY (\"id\")\n\
             );"
        );
    }

    #[test]
    fn composite_primary_key() {
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![col("a", "integer"), col("b", "integer")],
            pk_columns: vec!["a".into(), "b".into()],
        };
        assert!(table_ddl(&table).contains("PRIMARY KEY (\"a\", \"b\")"));
    }

    #[test]
    fn identity_column_emits_by_default_with_explicit_cache() {
        // Always emit GENERATED BY DEFAULT (never ALWAYS): the loader's
        // INSERT path supplies explicit id values, which a GENERATED ALWAYS
        // column rejects without OVERRIDING SYSTEM VALUE. BY DEFAULT accepts
        // them. DSQL also rejects identity without an explicit CACHE, and
        // identity implies NOT NULL so that clause is omitted.
        let id = ColumnDef {
            name: "id".into(),
            type_name: "bigint".into(),
            not_null: true,
            identity_cache: Some(1),
            default_expr: None,
        };
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![id],
            pk_columns: vec!["id".into()],
        };
        let ddl = table_ddl(&table);
        assert!(
            ddl.contains("\"id\" bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1)"),
            "got: {ddl}"
        );
        // Identity already implies NOT NULL — don't double it up.
        assert!(!ddl.contains("IDENTITY (CACHE 1) NOT NULL"), "got: {ddl}");
    }

    #[test]
    fn identity_cache_value_is_preserved() {
        let id = ColumnDef {
            name: "id".into(),
            type_name: "integer".into(),
            not_null: true,
            identity_cache: Some(128),
            default_expr: None,
        };
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![id],
            pk_columns: vec![],
        };
        assert!(
            table_ddl(&table).contains("GENERATED BY DEFAULT AS IDENTITY (CACHE 128)"),
            "got: {}",
            table_ddl(&table)
        );
    }

    #[test]
    fn column_default_is_emitted() {
        let mut status = col("status", "text");
        status.default_expr = Some("'active'::text".into());
        let table = TableDef {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![status],
            pk_columns: vec![],
        };
        assert!(
            table_ddl(&table).contains("\"status\" text DEFAULT 'active'::text"),
            "got: {}",
            table_ddl(&table)
        );
    }
}
