--
-- PostgreSQL database dump
--
-- DSQL-NATIVE full-dump fixture: the shape `pg_dump -Fp` emits when the SOURCE
-- is itself an Aurora DSQL cluster (captured verbatim from a real cluster via
-- the pgdump-proxy). Distinct from pgdump_full.sql (a vanilla-Postgres source)
-- because DSQL emits DDL it cannot itself re-ingest:
--   * identity PK as a standalone ALTER ... ADD GENERATED BY DEFAULT AS IDENTITY
--                          (dsql-lint 0.2.7 identity_idiom collapse)
--   * ALTER COLUMN ... SET COMPRESSION lz4
--                          (dsql-lint 0.2.7 set-compression strip)
--   * default_table_access_method = btree_table  (not heap)
--   * PRIMARY KEY (id) INCLUDE (<all cols>)       (covering PK; collapses fine)
--   * trailing SELECT setval(...)                 (lands on the implicit
--                                                  identity sequence; preserved)
-- Used by src/migrate/orchestrator.rs::dry_run_dsql_native_fixture to pin
-- --dry-run behavior offline.
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = btree_table;

--
-- Name: t; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t (
    id bigint NOT NULL,
    email text NOT NULL,
    payload json
);

ALTER TABLE ONLY public.t ALTER COLUMN payload SET COMPRESSION lz4;

--
-- Name: t id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Data for Name: t; Type: TABLE DATA; Schema: public
--

COPY public.t (id, email, payload) FROM stdin;
1	a@example.com	{"k":1}
2	b@example.com	[1,2,3]
\.

SELECT pg_catalog.setval('public.t_id_seq', 2, true);

--
-- Name: t t_email_key; Type: CONSTRAINT
--

ALTER TABLE ONLY public.t
    ADD CONSTRAINT t_email_key UNIQUE (email);

--
-- Name: t t_pkey; Type: CONSTRAINT
--

ALTER TABLE ONLY public.t
    ADD CONSTRAINT t_pkey PRIMARY KEY (id) INCLUDE (email, payload);

--
-- PostgreSQL database dump complete
--
