name: Scan for leaked secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan-for-leaks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      # Explicitly set permissions, following the principle of least privilege
      actions: read
      checks: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # For pull requests, check out the base branch, not the PR branch
        ref: ${{ github.event.pull_request.base.sha }}
    - name: gitleaks
      uses: gitleaks/gitleaks-action@v1.6.0
      env:
        # GitHub Token automatically created on run
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}